### ISSUE TITLE
Video thumbs are inaccessible

### ISSUE THREAD

**Issue by jaap3** [thomasw/pyposterous#2]
A video provides a 'thumb' field that doesn't look like the thumb field that comes with images. Instead it looks something like this:

```
<media>
<type>video</type>
[...]
<thumb>
http://posterous.com/getfile/video.posterous.com/temp-####-##-##/hash/frame_0000.png
</thumb>
</media>
```

When pyposterous is done with the XML the url of the thumb is not available.

**Comment by thomasw** [comment]
I'll check it out sometime today. Sorry about the trouble.

**Comment by thomasw** [comment]
I was able to confirm your issue. Pyposterous tries to treat the thumb attribute as an Image object and it fails to do so because it has no child elements. I'll see what I can do to fix it.

On another note: It looks like Posterous doesn't provide the thumb attribute until the video is done transcoding. In a way, that makes sense. They probably don't even have the thumbnail until then. So, if you post a video and then immediately retrieve it, the thumbnail attribute will most likely be unavailable and Posterous won't return it in the XML. If you retrieve it a little bit later, it should be there though.

**Comment by jaap3** [comment]
Not having a thumb element at all is probably the easiest way of checking if Posterous is done transcoding yet then :-).

Come to think of it, it seems that the MP4 element is always available even if the transcoding isn't done... strange. (Can't actually check right now if that's the case, but I fairly sure that statement is true).

**Comment by thomasw** [comment]
I just pushed a change that should address this problem: http://github.com/thomasw/pyposterous/commit/5d7b02ce87c6b284758c5f0882cb430b8aaa941a

Give it a go when you can and let me know how it goes. I'll wait to hear from you before tagging a new version and updating the documentation.

I also tested whether or not the mp4 attribute would be available:

These are the attributes available before transcoding completes: api, filesize, type, url

and these are the ones available after: api, filesize, mp4, thumb, type, url

URL is the path to the original file that was uploaded.

**Comment by jaap3** [comment]
I'll be able to test this on Thursday. Thanks for fixing and checking out my mp4 hunch!

**Comment by jaap3** [comment]
Getting thumbs from videos now work just fine, thanks!

**Comment by thomasw** [comment]
I've updated the ChangeLog and tagged a new release: http://github.com/thomasw/pyposterous/tree/0.3.2

Thanks for the help, jaap3.
